// Generated from showeq-daemon/src/zones.h — short → long zone-name lookup.
// The table covers every zone the daemon recognizes (~628 entries); the
// demo only resolves names for short names that exist in maps/, but
// shipping the full table keeps it useful for the opportunistic
// ~/.showeq/maps loader path too.

export const ZONE_LONG_NAMES: Record<string, string> = {
  qeynos: 'South Qeynos',
  qeynos2: 'North Qeynos',
  qrg: 'Surefall Glade',
  qeytoqrg: 'Qeynos Hills',
  highkeep: 'High Keep',
  freportn: 'North Freeport',
  freportw: 'West Freeport',
  freporte: 'East Freeport',
  runnyeye: 'The Liberated Citadel of Runnyeye',
  qey2hh1: 'The Western Plains of Karana',
  northkarana: 'The Northern Plains of Karana',
  southkarana: 'The Southern Plains of Karana',
  eastkarana: 'The Eastern Plains of Karana',
  beholder: 'The Gorge of King Xorbb',
  blackburrow: 'Blackburrow',
  paw: 'The Lair of the Splitpaw',
  rivervale: 'Rivervale',
  kithicor: 'Kithicor Forest',
  commons: 'West Commonlands',
  ecommons: 'East Commonlands',
  erudnint: 'Erudin Palace',
  erudnext: 'Erudin',
  nektulos: 'Nektulos Forest',
  cshome: 'Sunset Home',
  lavastorm: 'The Lavastorm Mountains',
  nektropos: 'nektropos',
  halas: 'Halas',
  everfrost: 'Everfrost Peaks',
  soldunga: 'Solusek\'s Eye',
  soldungb: 'Nagafen\'s Lair',
  misty: 'Misty Thicket',
  nro: 'The Northern Desert of Ro',
  sro: 'The Southern Desert of Ro',
  befallen: 'Befallen',
  oasis: 'The Oasis of Marr',
  tox: 'Toxxulia Forest',
  hole: 'The Ruins of Old Paineel',
  neriaka: 'Neriak - Foreign Quarter',
  neriakb: 'Neriak - Commons',
  neriakc: 'Neriak - Third Gate',
  neriakd: 'Neriak - Fourth Gate',
  najena: 'Najena',
  qcat: 'The Qeynos Aqueduct System',
  innothule: 'Innothule Swamp',
  feerrott: 'The Feerrott',
  cazicthule: 'Temple of Cazic-Thule',
  oggok: 'Oggok',
  rathemtn: 'The Rathe Mountains',
  lakerathe: 'Lake Rathetear',
  grobb: 'Grobb',
  aviak: 'Aviak',
  gfaydark: 'The Greater Faydark',
  akanon: 'Ak\'Anon',
  steamfont: 'The Steamfont Mountains',
  lfaydark: 'The Lesser Faydark',
  crushbone: 'Clan Crushbone',
  mistmoore: 'The Castle of Mistmoore',
  kaladima: 'South Kaladim',
  felwithea: 'Northern Felwithe',
  felwitheb: 'Southern Felwithe',
  unrest: 'The Estate of Unrest',
  kedge: 'Kedge Keep',
  guktop: 'The City of Guk',
  gukbottom: 'The Ruins of Old Guk',
  kaladimb: 'North Kaladim',
  butcher: 'Butcherblock Mountains',
  oot: 'The Ocean of Tears',
  cauldron: 'Dagnor\'s Cauldron',
  airplane: 'The Plane of Sky',
  fearplane: 'The Plane of Fear',
  permafrost: 'Permafrost Keep',
  kerraridge: 'Kerra Isle',
  paineel: 'Paineel',
  hateplane: 'The Plane of Hate',
  arena: 'The Arena',
  fieldofbone: 'The Field of Bone',
  warslikswood: 'The Warsliks Woods',
  soltemple: 'The Temple of Solusek Ro',
  droga: 'The Temple of Droga',
  cabwest: 'Cabilis West',
  swampofnohope: 'The Swamp of No Hope',
  firiona: 'Firiona Vie',
  lakeofillomen: 'Lake of Ill Omen',
  dreadlands: 'The Dreadlands',
  burningwood: 'The Burning Woods',
  kaesora: 'Kaesora',
  sebilis: 'The Ruins of Sebilis',
  citymist: 'The City of Mist',
  skyfire: 'The Skyfire Mountains',
  frontiermtns: 'Frontier Mountains',
  overthere: 'The Overthere',
  emeraldjungle: 'The Emerald Jungle',
  trakanon: 'Trakanon\'s Teeth',
  timorous: 'Timorous Deep',
  kurn: 'Kurn\'s Tower',
  erudsxing: 'Erud\'s Crossing',
  stonebrunt: 'The Stonebrunt Mountains',
  warrens: 'The Warrens',
  karnor: 'Karnor\'s Castle',
  chardok: 'Chardok',
  dalnir: 'The Crypt of Dalnir',
  charasis: 'Howling Stones',
  cabeast: 'Cabilis East',
  nurga: 'The Mines of Nurga',
  veeshan: 'Veeshan\'s Peak',
  veksar: 'Veksar',
  iceclad: 'The Iceclad Ocean',
  frozenshadow: 'The Tower of Frozen Shadow',
  velketor: 'Velketor\'s Labyrinth',
  kael: 'Kael Drakkel',
  skyshrine: 'Skyshrine',
  thurgadina: 'The City of Thurgadin',
  eastwastes: 'Eastern Wastes',
  cobaltscar: 'Cobalt Scar',
  greatdivide: 'The Great Divide',
  wakening: 'The Wakening Land',
  westwastes: 'The Western Wastes',
  crystal: 'Crystal Caverns',
  necropolis: 'Dragon Necropolis',
  templeveeshan: 'The Temple of Veeshan',
  sirens: 'Siren\'s Grotto',
  mischiefplane: 'The Plane of Mischief',
  growthplane: 'The Plane of Growth',
  sleeper: 'The Sleeper\'s Tomb',
  thurgadinb: 'Icewell Keep',
  erudsxing2: 'erudsxing2',
  shadowhaven: 'Shadow Haven',
  bazaar: 'The Bazaar',
  nexus: 'The Nexus',
  echo: 'Echo Caverns',
  acrylia: 'Acrylia Caverns',
  sharvahl: 'Shar Vahl',
  paludal: 'Paludal Caverns',
  fungusgrove: 'The Fungus Grove',
  vexthal: 'Vex Thal',
  sseru: 'Sanctus Seru',
  katta: 'Katta Castellum',
  netherbian: 'Netherbian Lair',
  ssratemple: 'Ssraeshza Temple',
  griegsend: 'Grieg\'s End',
  thedeep: 'The Deep',
  shadeweaver: 'Shadeweaver\'s Thicket',
  hollowshade: 'Hollowshade Moor',
  grimling: 'Grimling Forest',
  mseru: 'Marus Seru',
  letalis: 'Mons Letalis',
  twilight: 'The Twilight Sea',
  thegrey: 'The Grey',
  tenebrous: 'The Tenebrous Mountains',
  maiden: 'The Maiden\'s Eye',
  dawnshroud: 'Dawnshroud Peaks',
  scarlet: 'The Scarlet Desert',
  umbral: 'The Umbral Plains',
  akheva: 'The Akheva Ruins',
  arena2: 'Arenatwo',
  jaggedpine: 'Jaggedpine Forest',
  nedaria: 'Nedaria\'s Landing',
  tutorial: 'Tutorial',
  load: 'Load',
  load2: 'Loadtwo',
  hateplaneb: 'The Plane of Hate',
  shadowrest: 'Shadowrest',
  tutoriala: 'tutoriala',
  tutorialb: 'tutorialb',
  clz: 'clz',
  codecay: 'Ruins of Lxanvom',
  pojustice: 'The Plane of Justice',
  poknowledge: 'The Plane of Knowledge',
  potranquility: 'The Plane of Tranquility',
  ponightmare: 'The Plane of Nightmare',
  podisease: 'The Plane of Disease',
  poinnovation: 'The Plane of Innovation',
  potorment: 'Torment, the Plane of Pain',
  povalor: 'The Plane of Valor',
  bothunder: 'Torden, the Bastion of Thunder',
  postorms: 'The Plane of Storms',
  hohonora: 'The Halls of Honor',
  solrotower: 'The Tower of Solusek Ro',
  powar: 'The Plane of War',
  potactics: 'Drunder, the Fortress of Zek',
  poair: 'Eryslai, the Kingdom of Wind',
  powater: 'The Reef of Coirnav',
  pofire: 'Doomfire, the Burning Lands',
  poeartha: 'Vegarlson, The Earthen Badlands',
  potimea: 'The Plane of Time',
  hohonorb: 'The Temple of Marr',
  nightmareb: 'The Lair of Terris-Thule',
  poearthb: 'Ragrax, Stronghold of the Twelve',
  potimeb: 'The Prison of the Forsaken',
  gunthak: 'The Gulf of Gunthak',
  dulak: 'Dulak\'s Harbor',
  torgiran: 'The Torgiran Mines',
  nadox: 'The Crypt of Nadox',
  hatesfury: 'Hate\'s Fury',
  guka: 'Deepest Guk: Cauldron of Lost Souls',
  ruja: 'The Rujarkian Hills: Bloodied Quarries',
  taka: 'Takish-Hiz: Sunken Library',
  mira: 'Miragul\'s Menagerie: Silent Gallery',
  mmca: 'Mistmoore\'s Catacombs: Forlorn Caverns',
  gukb: 'Deepest Guk: Drowning Crypt',
  rujb: 'The Rujarkian Hills: Halls of War',
  takb: 'Takish-Hiz: Shifting Tower',
  mirb: 'Miragul\'s Menagerie: Maw of the Menagerie',
  mmcb: 'Mistmoore\'s Catacombs: Dreary Grotto',
  gukc: 'Deepest Guk: Ancient Aqueducts',
  rujc: 'The Rujarkian Hills: Wind Bridges',
  takc: 'Takish-Hiz: Fading Temple',
  mirc: 'Miragul\'s Menagerie: Spider Den',
  mmcc: 'Mistmoore\'s Catacombs: Asylum of Invoked Stone',
  gukd: 'Deepest Guk: Mushroom Grove',
  rujd: 'The Rujarkian Hills: Gladiator Pits',
  takd: 'Takish-Hiz: Royal Observatory',
  mird: 'Miragul\'s Menagerie: Hushed Banquet',
  mmcd: 'Mistmoore\'s Catacombs: Chambers of Eternal Affliction',
  guke: 'Deepest Guk: Foreboding Prison',
  ruje: 'The Rujarkian Hills: Drudge Hollows',
  take: 'Takish-Hiz: River of Recollection',
  mire: 'Miragul\'s Menagerie: Frosted Halls',
  mmce: 'Mistmoore\'s Catacombs: Sepulcher of the Damned',
  gukf: 'Deepest Guk: Chapel of the Witnesses',
  rujf: 'The Rujarkian Hills: Fortified Lair of the Taskmasters',
  takf: 'Takish-Hiz: Sandfall Corridors',
  mirf: 'Miragul\'s Menagerie: Forgotten Wastes',
  mmcf: 'Mistmoore\'s Catacombs: Ritualistic Summoning Grounds',
  gukg: 'Deepest Guk: Root Garden',
  rujg: 'The Rujarkian Hills: Hidden Vale',
  takg: 'Takish-Hiz: Balancing Chamber',
  mirg: 'Miragul\'s Menagerie: Heart of the Menagerie',
  mmcg: 'Mistmoore\'s Catacombs: Cesspits of Putrescence',
  gukh: 'Deepest Guk: Accursed Sanctuary',
  rujh: 'The Rujarkian Hills: Blazing Forge',
  takh: 'Takish-Hiz: Sweeping Tides',
  mirh: 'Miragul\'s Menagerie: Morbid Laboratory',
  mmch: 'Mistmoore\'s Catacombs: Aisles of Blood',
  ruji: 'The Rujarkian Hills: Arena of Chance',
  taki: 'Takish-Hiz: Antiquated Palace',
  miri: 'Miragul\'s Menagerie: Theater of Imprisoned Horrors',
  mmci: 'Mistmoore\'s Catacombs: Halls of Sanguinary Rites',
  rujj: 'The Rujarkian Hills: Barracks of War',
  takj: 'Takish-Hiz: Prismatic Corridors',
  mirj: 'Miragul\'s Menagerie: Grand Library',
  mmcj: 'Mistmoore\'s Catacombs: Infernal Sanctuary',
  chardokb: 'Chardok: The Halls of Betrayal',
  soldungc: 'The Caverns of Exile',
  abysmal: 'The Abysmal Sea',
  natimbi: 'Natimbi, the Broken Shores',
  qinimi: 'Qinimi, Court of Nihilia',
  riwwi: 'Riwwi, Coliseum of Games',
  barindu: 'Barindu, Hanging Gardens',
  ferubi: 'Ferubi, Forgotten Temple of Taelosia',
  snpool: 'Sewers of Nihilia, Pool of Sludge',
  snlair: 'Sewers of Nihilia, Lair of Trapped Ones',
  snplant: 'Sewers of Nihilia, Purifying Plant',
  sncrematory: 'Sewers of Nihilia, Emanating Crematory',
  tipt: 'Tipt, Treacherous Crags',
  vxed: 'Vxed, the Crumbling Caverns',
  yxtta: 'Yxtta, Pulpit of Exiles',
  uqua: 'Uqua, the Ocean God Chantry',
  kodtaz: 'Kod\'Taz, Broken Trial Grounds',
  ikkinz: 'Ikkinz, Chambers of Destruction',
  qvic: 'Qvic, Prayer Grounds of Calling',
  inktuta: 'Inktu\'Ta, the Unmasked Chapel',
  txevu: 'Txevu, Lair of the Elite',
  tacvi: 'Tacvi, the Broken Temple',
  qvicb: 'qvicb',
  wallofslaughter: 'Wall of Slaughter',
  bloodfields: 'The Bloodfields',
  draniksscar: 'Dranik\'s Scar',
  causeway: 'Nobles\' Causeway',
  chambersa: 'Proving Grounds',
  chambersb: 'Proving Grounds',
  chambersc: 'Proving Grounds',
  chambersd: 'Proving Grounds',
  chamberse: 'Proving Grounds',
  chambersf: 'Proving Grounds',
  provinggrounds: 'Muramite Proving Grounds',
  anguish: 'Anguish, the Fallen Palace',
  dranikhollowsa: 'Dranik\'s Hollows: Watering Hole',
  dranikhollowsb: 'Dranik\'s Hollows: Fire Pit',
  dranikhollowsc: 'Dranik\'s Hollows: Murkglider Hive',
  dranikhollowsd: 'Dranik\'s Hollows',
  dranikhollowse: 'Dranik\'s Hollows',
  dranikhollowsf: 'Dranik\'s Hollows',
  dranikhollowsg: 'Dranik\'s Hollows',
  dranikhollowsh: 'Dranik\'s Hollows',
  dranikhollowsi: 'Dranik\'s Hollows',
  dranikhollowsj: 'Dranik\'s Hollows',
  dranikcatacombsa: 'Catacombs of Dranik',
  dranikcatacombsb: 'Catacombs of Dranik',
  dranikcatacombsc: 'Catacombs of Dranik',
  draniksewersa: 'Sewers of Dranik',
  draniksewersb: 'Sewers of Dranik',
  draniksewersc: 'Sewers of Dranik',
  riftseekers: 'Riftseekers\' Sanctum',
  harbingers: 'Harbinger\'s Spire',
  dranik: 'The Ruined City of Dranik',
  broodlands: 'The Broodlands',
  stillmoona: 'Stillmoon Temple',
  stillmoonb: 'The Ascent',
  thundercrest: 'Thundercrest Isles',
  delvea: 'Lavaspinner\'s Lair',
  delveb: 'Tirranun\'s Delve',
  thenest: 'The Accursed Nest',
  guildlobby: 'Guild Lobby',
  guildhall: 'Guild Hall',
  barter: 'barter',
  illsalin: 'Ruins of Illsalin',
  illsalina: 'Illsalin Marketplace',
  illsalinb: 'Temple of the Korlach',
  illsalinc: 'The Nargilor Pits',
  dreadspire: 'Dreadspire Keep',
  drachnidhive: 'The Hive',
  drachnidhivea: 'The Hatchery',
  drachnidhiveb: 'The Cocoons',
  drachnidhivec: 'The Queen\'s Lair',
  westkorlach: 'Stoneroot Falls',
  westkorlacha: 'Chambers of Xill',
  westkorlachb: 'Caverns of the Lost',
  westkorlachc: 'Lair of the Korlach',
  eastkorlach: 'The Undershore',
  eastkorlacha: 'Snarlstone Dens',
  shadowspine: 'Shadowspine',
  corathus: 'Corathus Creep',
  corathusa: 'Sporali Caverns',
  corathusb: 'Corathus Lair',
  nektulosa: 'Shadowed Grove',
  arcstone: 'Arcstone, Isle of Spirits',
  relic: 'Relic, the Artifact City',
  skylance: 'Skylance',
  devastation: 'The Devastation',
  devastationa: 'The Seething Wall',
  rage: 'Sverag, Stronghold of Rage',
  ragea: 'Razorthorn, Tower of Sullon Zek',
  takishruins: 'Ruins of Takish-Hiz',
  takishruinsa: 'The Root of Ro',
  elddar: 'The Elddar Forest',
  elddara: 'Tunare\'s Shrine',
  theater: 'Theater of Blood',
  theatera: 'Deathknell, Tower of Dissonance',
  freeporteast: 'East Freeport',
  freeportwest: 'West Freeport',
  freeportsewers: 'Freeport Sewers',
  freeportacademy: 'Academy of Arcane Sciences',
  freeporttemple: 'Temple of Marr',
  freeportmilitia: 'Freeport Militia House',
  freeportarena: 'Arena',
  freeportcityhall: 'City Hall',
  freeporttheater: 'Theater',
  freeporthall: 'Hall of Truth',
  northro: 'North Desert of Ro',
  southro: 'South Desert of Ro',
  crescent: 'Crescent Reach',
  moors: 'Blightfire Moors',
  stonehive: 'Stone Hive',
  mesa: 'Goru`kar Mesa',
  roost: 'Blackfeather Roost',
  steppes: 'The Steppes',
  icefall: 'Icefall Glacier',
  valdeholm: 'Valdeholm',
  frostcrypt: 'Frostcrypt, Throne of the Shade King',
  sunderock: 'Sunderock Springs',
  vergalid: 'Vergalid Mines',
  direwind: 'Direwind Cliffs',
  ashengate: 'Ashengate, Reliquary of the Scale',
  highpasshold: 'Highpass Hold',
  commonlands: 'The Commonlands',
  oceanoftears: 'The Ocean of Tears',
  kithforest: 'kithforest',
  befallenb: 'befallenb',
  highpasskeep: 'highpasskeep',
  innothuleb: 'Innothule Swamp',
  toxxulia: 'Toxxulia Forest',
  mistythicket: 'Misty Thicket',
  kattacastrum: 'Katta Castrum',
  thalassius: 'Thalassius, the Coral Keep',
  atiiki: 'Jewel of Atiiki',
  zhisza: 'Zhisza, the Shissar Sanctuary',
  silyssar: 'Silyssar, New Chelsith',
  solteris: 'Solteris, the Throne of Ro',
  barren: 'Barren Coast',
  buriedsea: 'The Buried Sea',
  jardelshook: 'Jardel\'s Hook',
  monkeyrock: 'Monkey Rock',
  suncrest: 'Suncrest Isle',
  deadbone: 'Deadbone Reef',
  blacksail: 'Blacksail Folly',
  maidensgrave: 'Maiden\'s Grave',
  redfeather: 'Redfeather Isle',
  shipmvp: 'The Open Sea',
  shipmvu: 'The Open Sea',
  shippvu: 'The Open Sea',
  shipuvu: 'The Open Sea',
  shipmvm: 'The Open Sea',
  mechanotus: 'Fortress Mechanotus',
  mansion: 'Meldrath\'s Majestic Mansion',
  steamfactory: 'The Steam Factory',
  shipworkshop: 'S.H.I.P. Workshop',
  gyrospireb: 'Gyrospire Beza',
  gyrospirez: 'Gyrospire Zeka',
  dragonscale: 'Dragonscale Hills',
  lopingplains: 'Loping Plains',
  hillsofshade: 'Hills of Shade',
  bloodmoon: 'Bloodmoon Keep',
  crystallos: 'Crystallos, Lair of the Awakened',
  guardian: 'The Mechamatic Guardian',
  steamfontmts: 'The Steamfont Mountains',
  cryptofshade: 'Crypt of Shade',
  dragonscalea: 'Tinmizer\'s Wunderwerks',
  dragonscaleb: 'Deepscar\'s Den',
  oldfieldofbone: 'Field of Scale',
  oldkaesoraa: 'Kaesora Library',
  oldkaesorab: 'Kaesora Hatchery',
  oldkurn: 'Kurn\'s Tower',
  oldkithicor: 'Bloody Kithicor',
  oldcommons: 'Old Commonlands',
  oldhighpass: 'oldhighpass',
  thevoida: 'The Void',
  thevoidb: 'The Void',
  thevoidc: 'The Void',
  thevoidd: 'The Void',
  thevoide: 'The Void',
  thevoidf: 'The Void',
  thevoidg: 'The Void',
  oceangreenhills: 'Oceangreen Hills',
  oceangreenvillage: 'Oceangreen Village',
  oldblackburrow: 'Blackburrow',
  bertoxtemple: 'Temple of Bertoxxulous',
  discord: 'Korafax, Home of the Riders',
  discordtower: 'Citadel of the Worldslayer',
  oldbloodfield: 'Old Bloodfields',
  precipiceofwar: 'Precipice of War',
  olddranik: 'City of Dranik',
  toskirakk: 'Toskirakk',
  korascian: 'Korascian Warrens',
  rathechamber: 'Rathe Council Chamber',
  oldfieldofboneb: 'Field of Scale',
  crafthalls: 'Ngreth\'s Den',
  brellsrest: 'Brell\'s Rest',
  fungalforest: 'Fungal Forest',
  underquarry: 'The Underquarry',
  coolingchamber: 'The Cooling Chamber',
  shiningcity: 'Kernagir, the Shining City',
  arthicrex: 'Arthicrex',
  foundation: 'The Foundation',
  lichencreep: 'Lichen Creep',
  pellucid: 'Pellucid Grotto',
  stonesnake: 'Volska\'s Husk',
  brellstemple: 'Brell\'s Temple',
  convorteum: 'The Convorteum',
  brellsarena: 'Brell\'s Arena',
  weddingchapel: 'Wedding Chapel',
  weddingchapeldark: 'Wedding Chapel',
  dragoncrypt: 'Lair of the Fallen',
  feerrott2: 'The Feerrott',
  thulehouse1: 'House of Thule',
  thulehouse2: 'House of Thule, Upper Floors',
  housegarden: 'The Grounds',
  thulelibrary: 'The Library',
  well: 'The Well',
  fallen: 'Erudin Burning',
  morellcastle: 'Morell\'s Castle',
  somnium: 'Sanctum Somnium',
  alkabormare: 'Al\'Kabor\'s Nightmare',
  miragulmare: 'Miragul\'s Nightmare',
  thuledream: 'Fear Itself',
  neighborhood: 'Sunrise Hills',
  phylactery: 'Miragul\'s Phylactery',
  phinterior3a1: 'Three Room House Interior',
  phinterior1a1: 'One Room House Interior',
  phinterior3a2: 'Three Room House Interior',
  phinterior3a3: 'Three Room House Interior',
  phinterior1a2: 'One Room House Interior',
  phinterior1a3: 'One Room House Interior',
  phinterior1b1: 'One Room House Interior',
  phinterior1d1: 'Hermit\'s Hideaway Interior',
  argath: 'Argath, Bastion of Illdaera',
  arelis: 'Valley of Lunanyn',
  sarithcity: 'Sarith, City of Tides',
  rubak: 'Rubak Oseka, Temple of the Sea',
  beastdomain: 'Beasts\' Domain',
  resplendent: 'The Resplendent Temple',
  pillarsalra: 'Pillars of Alra',
  windsong: 'Windsong Sanctuary',
  cityofbronze: 'Erillion, City of Bronze',
  sepulcher: 'Sepulcher of Order',
  eastsepulcher: 'Sepulcher East',
  westsepulcher: 'Sepulcher West',
  shadowedmount: 'Shadowed Mount',
  guildhalllrg: 'Palatial Guild Hall',
  guildhallsml: 'Grand Guild Hall',
  plhogrinteriors1a1: 'One Bedroom House Interior',
  plhogrinteriors1a2: 'One Bedroom House Interior',
  plhogrinteriors3a1: 'Three Bedroom House Interior',
  plhogrinteriors3a2: 'Three Bedroom House Interior',
  plhogrinteriors3b1: 'Three Bedroom House Interior',
  plhogrinteriors3b2: 'Three Bedroom House Interior',
  plhdkeinteriors1a1: 'One Bedroom House Interior',
  plhdkeinteriors1a2: 'One Bedroom House Interior',
  plhdkeinteriors1a3: 'One Bedroom House Interior',
  plhdkeinteriors3a1: 'Three Bedroom House Interior',
  plhdkeinteriors3a2: 'Three Bedroom House Interior',
  plhdkeinteriors3a3: 'Three Bedroom House Interior',
  guildhall3: 'Modest Guild Hall',
  shardslanding: 'Shard\'s Landing',
  xorbb: 'Valley of King Xorbb',
  kaelshard: 'Kael Drakkel: The King\'s Madness',
  eastwastesshard: 'East Wastes: Zeixshi-Kar\'s Awakening',
  crystalshard: 'The Crystal Caverns: Fragment of Fear',
  breedinggrounds: 'The Breeding Grounds',
  eviltree: 'Evantil, the Vile Oak',
  grelleth: 'Grelleth\'s Palace, the Chateau of Filth',
  chapterhouse: 'Chapterhouse of the Fallen',
  pomischief: 'The Plane of Mischief',
  burnedwoods: 'The Burned Woods',
  chelsithreborn: 'Chelsith Reborn',
  poshadow: 'Plane of Shadow',
  heartoffear: 'Heart of Fear: The Threshold',
  phinteriortree: 'Evantil\'s Abode',
  interiorwalltest: 'Wall Wall Wall',
  heartoffearb: 'Heart of Fear: The Rebirth',
  heartoffearc: 'Heart of Fear: The Epicenter',
  bixiewarfront: 'Bixie Warfront',
  deadhills: 'The Dead Hills',
  ethernere: 'Ethernere Tainted West Karana',
  thevoidh: 'The Void',
  plhbixieint: 'Bixie Hive',
  towerofrot: 'Tower of Rot',
  arginhiz: 'Argin-Hiz',
  exalted: 'Sul Vius: Demiplane of Life',
  arxmentis: 'Arx Mentis',
  brotherisland: 'Brother Island',
  kattacastrumb: 'Katta Castrum: Deluge',
  dredge: 'Combine Dredge',
  endlesscaverns: 'Caverns of Endless Song',
  thuliasaur: 'Thuliasaur Island',
  degmar: 'Degmar, the Lost Castle',
  tempesttemple: 'Tempest Temple',
  plhpirateshipint: 'The Wayward Lady',
  gnomemtn: 'Gnome Memorial Mountain',
  drogab: 'The Temple of Droga',
  charasisb: 'Sathir\'s Tomb',
  scorchedwoods: 'The Scorched Woods',
  frontiermtnsb: 'Frontier Mountains',
  gorowyn: 'Gorowyn',
  korshaext: 'Gates of Kor-Sha',
  lceanium: 'Lceanium',
  cosul: 'Crypt of Sul',
  codecayb: 'Ruins of Lxanvom',
  exaltedb: 'Sul Vius: Demiplane of Decay',
  pohealth: 'The Plane of Health',
  korshaint: 'Kor-Sha Laboratory',
  chardoktwo: 'Chardok',
  charasistwo: 'Howling Stones',
  skyfiretwo: 'The Skyfire Mountains',
  overtheretwo: 'The Overthere',
  veeshantwo: 'Veeshan\'s Peak',
  trialsofsmoke: 'Plane of Smoke',
  stratos: 'Stratos: Zephyr\'s Flight',
  aalishai: 'Aalishai: Palace of Embers',
  empyr: 'Empyr: Realms of Ash',
  esianti: 'Esianti: Palace of the Winds',
  mearatas: 'Mearatas: The Stone Demesne',
  chamberoftears: 'Chamber of Tears',
  eastwastestwo: 'The Eastern Wastes',
  frozenshadowtwo: 'The Tower of Frozen Shadow',
  crystaltwoa: 'The Ry`Gorr Mines',
  greatdividetwo: 'The Great Divide',
  velketortwo: 'Velketor\'s Labyrinth',
  kaeltwo: 'Kael Drakkel',
  crystaltwob: 'Crystal Caverns',
  sleepertwo: 'The Sleeper\'s Tomb',
  necropolistwo: 'Dragon Necropolis',
  cobaltscartwo: 'Cobalt Scar',
  westwastestwo: 'The Western Wastes',
  skyshrinetwo: 'Skyshrine',
  templeveeshantwo: 'The Temple of Veeshan',
  'clz-winter': 'Winter',
  'clz-anniversary': 'Anniversary',
  'clz-spring': 'Spring',
  'clz-autumn': 'Autumn',
  'clz-frostfell': 'Frostfell',
  'clz-af': 'April Fools',
  maidentwo: 'Maiden\'s Eye',
  umbraltwo: 'Umbral Plains',
  akhevatwo: 'Ka Vethan',
  vexthaltwo: 'Vex Thal',
  shadowvalley: 'Shadow Valley',
  basilica: 'Basilica of Adumbration',
  bloodfalls: 'Bloodfalls',
  maidenhouseint: 'Coterie Chambers',
  shadowhaventwo: 'Ruins of Shadow Haven',
  sharvahltwo: 'Shar Vahl, Divided',
  paludaltwo: 'Paludal Depths',
  shadeweavertwo: 'Shadeweaver\'s Tangle',
  darklightcaverns: 'Darklight Caverns',
  deepshade: 'Deepshade',
  firefallpass: 'Firefall Pass',
  hollowshadetwo: 'Hollowshade Moor',
  laurioninn: 'Laurion Inn',
  ankexfen: 'Ankexfen Keep',
  pallomen: 'Pal\'Lomen',
  herosforge: 'The Hero\'s Forge',
  moorsofnokk: 'Moors of Nokk',
  unkemptwoods: 'Unkempt Woods',
  timorousfalls: 'Timorous Falls',
  'clz-tempest': 'Tempest Festival',
  anniversarytower: 'Tides of Time',
  hodstock: 'Hodstock Hills',
  toe: 'The Theater of Eternity',
  aureatecovert: 'Aureate Covert',
  harbingerscradle: 'The Harbinger\'s Cradle',
  puissance: 'The Chambers of Puissance',
  gildedspire: 'The Gilded Spire',
  'clz-25anniversary': 'Anniversary',
  dragonhouseinta: 'Aureate Chalet Three Room',
  dragonhouseintb: 'Aureate Chalet One Room',
  candlemakers: 'Candlemaker\'s Workshop',
  embattledpogrowth: 'Scarred Grove',
  arcstoneruins: 'Arcstone, Shattered Isles',
  ruinedrelic: 'Ruined Relic',
  vortex: 'The Vortex',
  spite: 'Labyrinth of Spite',
  guildhallsng: 'Grand Guild Hall',
  giftygiver: 'The Gifty Giver',
  'clz-brewday': 'Brew Day',
  arttest: 'The Pit of Rathpher',
  fhalls: 'The Forgotten Halls',
  apprentice: 'Plane of Noob',
};
